# LuCI ATMaterial Theme
# Copyright 2016 "panda-mute" <https://github.com/panda-mute>
# Copyright 2017 "monokoo" <https://github.com/monokoo>
# Copyright 2019 William Rogers <https://github.com/solidus1983>
# Copyright 2019 Jose Olivera <oliverajeo@gmail.com>
#
# Licensed under the Apache License v2.0
# http://www.apache.org/licenses/LICENSE-2.0

include $(TOPDIR)/rules.mk

LUCI_TITLE:=ATMaterial
LUCI_DEPENDS:=

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
